language: node_js
node_js:
  - "6.11"
#
# Install dependencies
#
before_install:
  - npm install -g @angular/cli

install:
  - npm install

#
# build the project
#
script:
  - ng build --prod --base-ref /barcode-generator/

#
# Deploy to gh-pages branch on github
#
# Doc: https://docs.travis-ci.com/user/deployment/pages/
#
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true

  on:
    branch: master
